### ISSUE TITLE
IINA asks if I want beta updates (v1.0 is coming soon!) when downloading 1.0.4

### ISSUE THREAD

**Issue by valtism** [iina/iina#2504]
This happened on a fresh new clean install of Mojave. I downloaded IINA v1.0.4 and when I opened it for the first time, I got the message saying that v1.0 is coming soon, and asking me if I want to receive updates for the beta version.

I believe this should not be present in a post 1.0 build, or at least remove the mention of v1.0 coming soon.

- macOS Mojave
- IINA 1.0.4

**Expected behavior:**

No popup on first open.

**Actual behavior:**

Popup asking me if I want to receive beta updates because v1.0 is coming soon.

**Steps to reproduce:**

Download IINA 1.0.4 and install on a machine with no history of an IINA install (clean). Will see popup on first open.

**Comment by alejx** [comment]
Thanks. This has been fixed in the develop branch.

**Comment by ikir83** [comment]
Still happening now, first time running the app it says 1.0 is coming and join beta. Even with 1.06
