### ISSUE TITLE
Provide option to dock sidebar to the window, instead of sliding out

### ISSUE THREAD

**Issue by vjpr** [iina/iina#2629]
My use case is that I want to navigate through a playlist of videos. When the sidebar is open it covers a part of the video.

**Comment by marcinretecki** [comment]
I second this. It is also problematic to seek time because playlist is over the slider.

**Comment by jerkstore369** [comment]
This has been asked before a while ago so I don't know why it hasn't been addressed.

**Comment by ruslaniv** [comment]
Yes, this needs to be implemented! 
I have educational videos, organized into lectures where each lecture consists of several video segments and I have to keep the playlist window open to navigate between different lecture segments. 
If I keep the playlist open, it covers part of the screen, the **EXACT** part of the screen where the blackboard is!!!

**Comment by ruslaniv** [comment]
> I second this. It is also problematic to seek time because playlist is over the slider.

But can't you move the controls window from under the playlist window?

**Comment by uiryuu** [comment]
Fixed in #6132.

**Comment by ruslaniv** [comment]
How is this fixed? 
I am on latest version `IINA 1.4.3 is currently the newest version available.` and i still can't have the sidebar NOT to cover part of the screen

**Comment by uiryuu** [comment]
This feature has been partially implemented in the `develop` branch and will be included in the next major release of IINA (v1.5.0). Further improvements, adjustments, and bug fixes related to this issue are expected. If you're interested, you can try it out by downloading a [Nightly build](https://iina.io/nightly/) (a GitHub account is required).
