### ISSUE TITLE
App becomes unresponsive when typing in "Preferred language" text field

### ISSUE THREAD

**Issue by alejx** [iina/iina#2806]
**System and IINA version:**

- macOS 10.15 (probably from 10.14 or earlier?)
- IINA 1.0.7 beta (and earlier versions)

As a workaround, you can always copy and paste into the text field.

**Comment by allie** [comment]
I haven't really verified that this is an appropriate fix, but unchecking `Continuously Updates Value` for those fields in the interface builder keeps the infinite loop from occurring.

**Comment by mediter** [comment]
setting "Preferred language" in "Subtitle" section of Preferences would cause the app to consistently crash.

IINA 1.0.7-beta1 (115)
macOS 10.15.3 (19D76)

**Comment by spiderknight** [comment]
Verified workaround: you can paste your 3-letter ISO code and hit RETURN without crash

**Comment by MatthiasWinkelmann** [comment]
Here's what Apple wants to phone home about such a crash:

````
Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [1055]

Application Specific Information:
Crashing on exception: The window has been marked as needing another Update Constraints in Window pass, but it has already had more Update Constraints in Window passes than there are views in the window.

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff34ebc8ab __exceptionPreprocess + 250
1   libobjc.A.dylib                     0x00007fff6af94805 objc_exception_throw + 48
2   CoreFoundation                      0x00007fff34ebc701 +[NSException raise:format:] + 189
3   AppKit                              0x00007fff32048735 -[NSWindow(NSDisplayCycle) _postWindowNeedsUpdateConstraintsUnlessPostingDisabled] + 1590
4   AppKit                              0x00007fff3202b1a0 -[NSView _informContainerThatSubviewsNeedUpdateConstraints] + 59
5   AppKit                              0x00007fff3202b1a0 -[NSView _informContainerThatSubviewsNeedUpdateConstraints] + 59
6   AppKit                              0x00007fff3202b1a0 -[NSView _informContainerThatSubviewsNeedUpdateConstraints] + 59
7   AppKit                              0x00007fff3202b1a0 -[NSView _informContainerThatSubviewsNeedUpdateConstraints] + 59
8   AppKit                              0x00007fff3202b1a0 -[NSView _informContainerThatSubviewsNeedUpdateConstraints] + 59
9   AppKit                              0x00007fff3202b1a0 -[NSView _informContainerThatSubviewsNeedUpdateConstraints] + 59
10  AppKit                              0x00007fff3202b1a0 -[NSView _informContainerThatSubviewsNeedUpdateConstraints] + 59
11  AppKit                              0x00007fff3202b1a0 -[NSView _informContainerThatSubviewsNeedUpdateConstraints] + 59
12  AppKit                              0x00007fff3202b11a -[NSView setNeedsUpdateConstraints:] + 551
13  AppKit                              0x00007fff3202e80d -[NSView(NSConstraintBasedLayout) _invalidateIntrinsicContentSizeDirtyingConstraints:] + 119
14  AppKit                              0x00007fff3204bc7c -[NSTextField invalidateIntrinsicContentSize] + 42
15  AppKit                              0x00007fff3204b2e0 -[NSCell setObjectValue:] + 374
16  AppKit                              0x00007fff3211a749 -[NSTokenFieldCell setObjectValue:] + 197
17  AppKit                              0x00007fff3204f24f -[NSCell setAttributedStringValue:] + 233
18  AppKit                              0x00007fff323e0862 -[NSTokenFieldCell _validateEditing:] + 76
19  AppKit                              0x00007fff3204cf2a -[NSCell attributedStringValue] + 92
20  AppKit                              0x00007fff320bfc95 -[NSTextField _performMultiPassIntrinsicSize] + 258
21  AppKit                              0x00007fff320bf9a5 -[NSTextField updateConstraints] + 47
22  AppKit                              0x00007fff320bdb5c _NSViewUpdateConstraints + 95
23  AppKit                              0x00007fff320bd851 -[NSView _updateConstraintsForSubtreeIfNeededCollectingViewsWithInvalidBaselines:] + 839
24  AppKit                              0x00007fff320bd69c -[NSView _updateConstraintsForSubtreeIfNeededCollectingViewsWithInvalidBaselines:] + 402
25  AppKit                              0x00007fff320bd69c -[NSView _updateConstraintsForSubtreeIfNeededCollectingViewsWithInvalidBaselines:] + 402
26  AppKit                              0x00007fff320bd69c -[NSView _updateConstraintsForSubtreeIfNeededCollectingViewsWithInvalidBaselines:] + 402
27  AppKit                              0x00007fff320bd69c -[NSView _updateConstraintsForSubtreeIfNeededCollectingViewsWithInvalidBaselines:] + 402
28  AppKit                              0x00007fff320bd69c -[NSView _updateConstraintsForSubtreeIfNeededCollectingViewsWithInvalidBaselines:] + 402
29  AppKit                              0x00007fff320bd69c -[NSView _updateConstraintsForSubtreeIfNeededCollectingViewsWithInvalidBaselines:] + 402
30  AppKit                              0x00007fff320bd69c -[NSView _updateConstraintsForSubtreeIfNeededCollectingViewsWithInvalidBaselines:] + 402
31  AppKit                              0x00007fff320ceb6c __82-[NSView _updateConstraintsForSubtreeIfNeededCollectingViewsWithInvalidBaselines:]_block_invoke + 274
32  Foundation                          0x00007fff374f7c13 -[NSISEngine withBehaviors:performModifications:] + 84
33  AppKit                              0x00007fff320bd5b3 -[NSView _updateConstraintsForSubtreeIfNeededCollectingViewsWithInvalidBaselines:] + 169
34  AppKit                              0x00007fff320bd421 __45-[NSView updateConstraintsForSubtreeIfNeeded]_block_invoke + 48
35  Foundation                          0x00007fff374f7c13 -[NSISEngine withBehaviors:performModifications:] + 84
36  AppKit                              0x00007fff32020d94 -[NSView(NSConstraintBasedLayout) _withAutomaticEngineOptimizationDisabled:] + 59
37  AppKit                              0x00007fff320bd209 -[NSView updateConstraintsForSubtreeIfNeeded] + 209
38  AppKit                              0x00007fff320ebab1 __62-[NSWindow(NSConstraintBasedLayout) updateConstraintsIfNeeded]_block_invoke + 154
39  Foundation                          0x00007fff374f7c13 -[NSISEngine withBehaviors:performModifications:] + 84
40  AppKit                              0x00007fff32020d94 -[NSView(NSConstraintBasedLayout) _withAutomaticEngineOptimizationDisabled:] + 59
41  AppKit                              0x00007fff320eb9bf -[NSWindow(NSConstraintBasedLayout) updateConstraintsIfNeeded] + 235
42  AppKit                              0x00007fff320eb80f __NSWindowGetDisplayCycleObserverForUpdateConstraints_block_invoke + 430
43  AppKit                              0x00007fff320eb621 NSDisplayCycleObserverInvoke + 155
44  AppKit                              0x00007fff320eb1e8 NSDisplayCycleFlush + 977
45  QuartzCore                          0x00007fff40647112 _ZN2CA11Transaction19run_commit_handlersE18CATransactionPhase + 100
46  QuartzCore                          0x00007fff40645e64 _ZN2CA11Transaction6commitEv + 224
47  AppKit                              0x00007fff321a7e87 __62+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayLink]_block_invoke + 266
48  AppKit                              0x00007fff328c377d ___NSRunLoopObserverCreateWithHandler_block_invoke + 41
49  CoreFoundation                      0x00007fff34e400ee __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
50  CoreFoundation                      0x00007fff34e40014 __CFRunLoopDoObservers + 457
51  CoreFoundation                      0x00007fff34e3f70b __CFRunLoopRun + 1219
52  CoreFoundation                      0x00007fff34e3ebd3 CFRunLoopRunSpecific + 499
53  HIToolbox                           0x00007fff3399565d RunCurrentEventLoopInMode + 292
54  HIToolbox                           0x00007fff339952a9 ReceiveNextEventCommon + 356
55  HIToolbox                           0x00007fff33995127 _BlockUntilNextEventMatchingListInModeWithFilter + 64
56  AppKit                              0x00007fff32006eb4 _DPSNextEvent + 990
57  AppKit                              0x00007fff32005690 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
58  AppKit                              0x00007fff31ff73ae -[NSApplication run] + 658
59  AppKit                              0x00007fff31fc9775 NSApplicationMain + 777
60  IINA                                0x00000001078f8a49 main + 9
61  libdyld.dylib                       0x00007fff6c3027fd start + 1

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.apple.AppKit              	0x00007fff323e84b7 -[NSApplication _crashOnException:] + 106
1   com.apple.AppKit              	0x00007fff321a80a2 __62+[CATransaction(NSCATransaction) NS_setFlushesWithDisplayLink]_block_invoke + 805
2   com.apple.AppKit              	0x00007fff328c377d ___NSRunLoopObserverCreateWithHandler_block_invoke + 41
3   com.apple.CoreFoundation      	0x00007fff34e400ee __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
4   com.apple.CoreFoundation      	0x00007fff34e40014 __CFRunLoopDoObservers + 457
5   com.apple.CoreFoundation      	0x00007fff34e3f70b __CFRunLoopRun + 1219
6   com.apple.CoreFoundation      	0x00007fff34e3ebd3 CFRunLoopRunSpecific + 499
7   com.apple.HIToolbox           	0x00007fff3399565d RunCurrentEventLoopInMode + 292
8   com.apple.HIToolbox           	0x00007fff339952a9 ReceiveNextEventCommon + 356
9   com.apple.HIToolbox           	0x00007fff33995127 _BlockUntilNextEventMatchingListInModeWithFilter + 64
10  com.apple.AppKit              	0x00007fff32006eb4 _DPSNextEvent + 990
11  com.apple.AppKit              	0x00007fff32005690 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
12  com.apple.AppKit              	0x00007fff31ff73ae -[NSApplication run] + 658
13  com.apple.AppKit              	0x00007fff31fc9775 NSApplicationMain + 777
14  com.colliderli.iina           	0x00000001078f8a49 main + 9
15  libdyld.dylib                 	0x00007fff6c3027fd start + 1
````

**Comment by amjd** [comment]
I encountered this as well. My experience was the same as @spiderknight's. Typing consistently makes the app crash but directly pasting the language code works.

**Comment by francisceril** [comment]
Having same issue with below specs:

macOS 10.15.4
IINA 1.0.7-beta1 Build 115

**Comment by lhc70000** [comment]
Seems that `NSTokenField` doesn't work well with cocoa binding. Fixed in the 1.0.7 branch and will be available in 1.0.7 beta2.

**Comment by johnathanz** [comment]
Issue still happening.

Steps to reproduce:
1) Open IINA (with or without movie)
2) Settings > Subtitles > Type in Subtitle (e.g. `eng`), click the language from the autoselect
3) Close Settings

What happens
IINA crashs - everytime. On restarting, subtitle language still empty

What did I expect
Settings to close and subtitle language

---

IINA 1.1.2 Build 128
mpv 0.32.0

Mac OSX 10.14.6 (18G8022)
