### ISSUE TITLE
Custom key binding ignored

### ISSUE THREAD

**Issue by low-batt** [iina/iina#3692]
**System and IINA version:**

- macOS 12.3.1
- IINA 1.2.0

**Expected behavior:**
When a key is pressed IINA executes the commands assigned in a custom key binding.

**Actual behavior:**
IINA ignored the key binding.

<br>

**Steps to reproduce:**
- Open IINA / Preferences
- Click on `Key Bindings`
- Select `IINA Default`
- Click `Duplicate`
- Click `+` to add a new binding
- Add an additional binding for the `RIGHT` (arrow) key with the action `seek 60 exact`
- Add an additional binding for the `LEFT` (arrow) key with the action `seek -60 exact`
- This adds a **second** definition for these keys
- Restart IINA to insure new preferences are being used
- Play video
- Open `Playback` menu
- Notice that the menu item `Step Forward 5s` is still bound to the right arrow key
- Notice that the menu item `Step Backward 5s` is still bound to the left arrow key
- Test the right and left arrow keys
- New binding are ignored and IINA continues to seek by 5 seconds

- [ ] MPV does not have this problem.

This is a problem in IINA.

**How often does this happen?**
Every time.

I will post an analysis of the root cause and a proposed fix.

**Comment by low-batt** [comment]
### Analysis

Custom IINA key bindings are stored in a mpv [input.conf](https://mpv.io/manual/master/#input-conf) configuration file. These files can be found in the directory `~/Library/Application\ Support/com.colliderli.iina/input_conf`:
```bash
low-batt@gag ~$ cd ~/Library/Application\ Support/com.colliderli.iina/input_conf/
low-batt@gag input_conf$ ls
issue-3692.conf
low-batt@gag input_conf$
```
Each line of an `input.conf` file maps a key to an input command. Neither IINA nor mpv enforce a requirement that the configuration file only contains one entry for a particular key even though the result of processing the configuration file results in a one to one binding between a key and an input command (ignoring mpv's ability to bind a sequence of keys). So what happens if the configuration file contains duplicate entries for a key? IINA should match mpv's behavior. I did not find this discussed in the mpv manual. This  `input.conf` file was tested with mpv:
```text
RIGHT seek 5
LEFT seek -5
RIGHT quit
LEFT quit
```
When the right arrow key was clicked mpv shutdown. The convention seems to be that if there are duplicates, last definition wins. What you would expect if each line of the configuration file is being processed and added to a unique key to input command mapping without checking for an existing entry.

IINA should match up with the behavior of mpv. In the case at hand it does not. The offending code is in `MenuController.updateKeyEquivalentsFrom`. This loop:
```swift
for kb in keyBindings {
```
Is iterating through an array of `KeyBinding` objects. As shown by this debug logging these object directly represent the entries in the configuration file:
```text
18:13:54.359 [iina][d] RIGHT ["seek", "5"]
18:13:54.359 [iina][d] LEFT ["seek", "-5"]
...
18:13:54.360 [iina][d] RIGHT ["seek", "60", "exact"]
18:13:54.360 [iina][d] LEFT ["seek", "-60", "exact"]
```
The array is being searched for keys that should be assigned as a shortcut for a menu item. The search is looking for a binding that matches the action of the menu item. The loop matches "seek", "5" with the `Playback` menu item `Step Forward 5s` and assigns the right arrow key to that menu item, even though that key binding should have been ignored due to the reassignment later in the configuration file. Thus when the right arrow key is pressed the menu item is invoked and the video seeks forward by 5 seconds instead of 60. IINA should have not assigned a keyboard shortcut to the menu item in this case.

### Fixing

The proposed fix in the pull request changes `updateKeyEquivalentsFrom` to create an array with any overridden bindings removed:
```swift
let activeBindings = keyBindings.reversed().uniqued(on: \.key).reversed()
```
That array is then searched instead of `keyBindings`.

The commit adds the package [Swift Algorithms](https://github.com/apple/swift-algorithms) to be able to use the `uniqued` method.

**Comment by varenc** [comment]
This is awesome! I've dealt with IINA's idiosyncratic keybinding treatment and have definitely ran into this before.  I would love IINA's keybindings to be more consistent with mpv's.  

Stepping back a bit, do you know the rational for IINA re-implementing mpv's input.conf parsing and command execution instead of just relying on mpv's? It's pretty odd that it's entirely separate. Also IINA's input.conf parsing is missing features that mpv supports like `{sections}` or key sequence commands.

For example, here's a wonderful/horrible hack in my input.conf that illustrates some of these issue:

```
d-d {mpv-only} add chapter 1;
d {mpv-only} ignore
d keypress "Meta+Alt+F12"
Meta+Alt+F12-Meta+Alt+F12 add chapter 1;
```

The goal here to bind the key sequence "d - d" to `add chapter 1` and have that **work in IINA or mpv**.

Notes:
- `d-d` means "press d, then press d again" and is supported by mpv, but not IINA
- IINA's input.conf parsing doesn't understand the `{mpv-only}` section marks so it just ignores those lines.
- The line with `Meta+Alt+F12-Meta+Alt+F12` is also ignored by IINA's parsing, since IINA doesn't understand sequences, but it is not ignored by mpv's input parsing, which also runs inside of IINA.
- I have things configured so the `{mpv-only}` section is only enabled when vanilla mpv is ran, not IINA. Those just exist to support the same behavior when I use the same input.conf with mpv.

This ridiculous hack makes `d-d` work in IINA by relying on the fact that behind the scenes IINA still runs the mpv input.conf parsing and keybinding, which supports sequences, but it just never fires them.   When IINA receives a keypress is just pairs that up with its input.conf parsing of what the command should be instead of relying on mpv's version. So when IINA sees `d` it fires a keypress at the mpv level by just calling `keypress "Meta+Alt+F12"`.  IINA doesn't support key sequences, but mpv does, so when `d` is pressed again, another `keypress "Meta+Alt+F12"` is called, which mpv then correctly interprets as the second press and runs `add chapter 1`.

I will say one nice advantage of the IINA approach is that you can swap out all of your keybindings without restarting. This is something mpv doesn't support.  Though that does put you in a weird state if you change your bindings because now if you run a `keypress ...` command that's a keypress at the mpv level, where the keybindings haven't been updated, so that'll run the old command binding and not the updated bindings at the IINA level.  Puts you in a state where pressing "x" and firing running the command `keypress x` could do totally different things.

Anyway, that was a lot of text. Just wanted to brain dump some thoughts/observations about IINA's keybinding treatment here since it seems relevant.  Cheers!

**Comment by low-batt** [comment]
Thanks for posting this. Very helpful to me. I'm new to IINA. This is the first time I looked closely into the IINA key binding code. One of the restrictions I don't like is that dynamic key bindings established by mpv Lua scripts do not work in IINA. Some of the restrictions you cited I suspect prevent implementation of the J-K-L key binding requested in issue #3224.

I believe there are a couple of key bindings missing from the mpv set. Keys the mpv project have added. I plan on looking into that at some point.

**Comment by lhc70000** [comment]
The cause of this problem is:

1. IINA tries to find a close match for each menu item. There's only one menu action, but the conf file may have multiple seeking commands, like `A -> seek 10` `B -> seek 20` etc. The rule is, for the seek action, it will find the last command that match this range `seek 5-10`.   https://github.com/iina/iina/blob/9427486ddc59c96a3441e0b78fda71cac598aa06/iina/MenuController.swift#L651-L652
  If you add a command `→ -> seek 60`, it won't be assigned to the menu item, so `→ -> seek 5` is still bound to the menu item.
2. However, IINA won't keep duplicated keybindings. After updating the menu items, it will build a `Dictionary` of the key bindings, where later ones will overwrite previous ones. So actually `→ -> seek 5` is removed here. https://github.com/iina/iina/blob/9427486ddc59c96a3441e0b78fda71cac598aa06/iina/PlayerCore.swift#L287
3. Therefore, it created an inconsistency: the action bound to the menu item is still `seek 5`, but internally we only have `seek 60`.
4. In macOS, menu actions take precedence over window key events. So the `→` key will be handled by the menu first and never propagated to the window, so the correct internal record will never work.

This is kind of awkward, but it's how macOS works. Since the menu action and window event are two different things, we have to implement our own key binding system and handle them separately.

---

I think a better fix is using the dictionary in step 2 (`keyBindings` rather than `keyMappings`) to update the menu key bindings to preserve the consistency.
https://github.com/iina/iina/blob/9427486ddc59c96a3441e0b78fda71cac598aa06/iina/PlayerCore.swift#L289

I will also update the range to `seek 5-60`, so `seek 60` will bind to the menu item. The current range is indeed to tight.

**Comment by low-batt** [comment]
The fix in PR #3728 has been merged into develop.

**Comment by low-batt** [comment]
Closing. Fixed in IINA 1.3.0.

**Comment by ba10blu** [comment]
its not fixed, I am afraid in the latest 1.3.1 Build 133, even after changing the binding keys the video forwards and then 30 sec it defaults

**Comment by talhakabakus** [comment]
Same for me on the latest available build for macOS, `1.3.3 Build 138`.

**Comment by RobinWragg** [comment]
Still not fixed for me in 1.3.5, build 141, macOS.
