### ISSUE TITLE
Play the hlg video recorded by DJI Mavic pro, all of which are overexposed

### ISSUE THREAD

**Issue by HangWangWH** [iina/iina#4441]
We use the iina player on the mac to play the hlg videos recorded by DJI Mavic pro, all of which are overexposed and very bright, but there is no such problem when playing dlog/normal videos.

We use vlc on the mac to play the hlg video, but there is no such phenomenon.

We have two doubts:

1. The high probability is that the player has post-processing and there is a problem with the post-processing.

2. The player uses a certain parameter packaged by our DJI for post-processing, but the wrong parameter causes problems.

we need to:

1. The iina developer informs us whether there is video post-processing and whether there is a problem with the post-processing.

2. If you use a certain parameter, please let us know, we will check the parameter and fix the problem.

Thanks!

Let's make iina player better together!

By DJI engineer .

**Comment by low-batt** [comment]
@HangWangWH, Sorry about the trouble!

I was able to find a HLG sample from a DJI drone. Playing that video with IINA 1.3.1 (the latest release) the picture is definitely too bright. I believe I reproduced the problem reported in this issue, however without a specific video sample I can't be absolutely certain.

There is a known issue with IINA's HDR implementation that is responsible for this. That issue has been fixed in the development version of IINA. When I played the video using the development version of IINA the picture was no longer too bright and looked like it does when played with QuickTime.

To confirm the problem has been addressed you can try the latest nightly build of the development version of IINA. Unsigned nightly builds can be downloaded [here](https://nightly.iina.io/). The new version of IINA adds support for tone mapping. That can be enabled in IINA's settings under the `Video/Audio` tab.

If you still see a problem when using the development version of IINA then we would need a video file that exhibits the problem.

As can be seen from the pinned issue IINA is very close to releasing a new version with updated HDR support.

**Comment by monzetsushonen** [comment]
Hi 
This issue was solved in latest version
just update it

**Comment by LeoNatan** [comment]
The issue is not solved, it still reproduces. All HDR content is too bright in iina, including latest 1.4.0 beta 1.

**Comment by low-batt** [comment]
@LeoNatan Have you checked the `Enable tone mapping` setting found on the `Video/Audio` tab of IINA's settings?

Do you see the same problem playing the YouTube video [The World in HDR in 4K (ULTRA HD)](https://www.youtube.com/watch?v=tO01J-M3g0U)?

What kind of display? What is the peak brightness?

Most, but not all, video support comes from `libmpv`. This is why the IINA issue template contains this optional question:
> - [ ]  I tested with the latest version of mpv and confirmed mpv doesn't have this issue.

If the [mpv player](https://mpv.io/) exhibits the same problem it will need to be fixed by that project.

If you run mpv like so (assuming you downloaded the above referenced YouTube video into your `Movies` directory), filling in the proper peak nits for your display:
```text
mpv --no-config --autofit=90% --cocoa-cb-output-csp=bt.2100-pq --target-peak=1600 --target-prim=bt.2020 --target-trc=pq --vo=libmpv ~/Movies/The\ World\ in\ HDR\ in\ 4K\ \(ULTRA\ HD\).mp4
```

Does the picture also see too bright?

Many of the improvements mpv has made related to HDR require use of their experimental next generation renderer. Unfortunately that render is not yet available to `libmpv` clients as of yet. Still it is useful to see if the problem is fixed in mpv's new renderer.

To test this invoke mpv with the [target-colorspace-hint](https://mpv.io/manual/stable/#options-target-colorspace-hint)  and [vo](https://mpv.io/manual/stable/#video-output-drivers-vo) options like so:
```text
mpv --no-config --autofit=90% --target-colorspace-hint=yes --vo=gpu-next ~/Movies/The\ World\ in\ HDR\ in\ 4K\ \(ULTRA\ HD\).mp4
```

At least that was working when I tried it under mpv 0.39.0. I just tried it now with mpv 0.40.0 and it did not seem to be activating [Extended Dynamic Range](https://developer.apple.com/documentation/metal/hdr_content/displaying_hdr_content_in_a_metal_layer#3335505). I'm going to have to look into what changed in mpv 0.40.0.

You can see some of the improvements that are coming with mpv's next generation renderer in issue #5298.

**Comment by LeoNatan** [comment]
I am using a MacBook Pro XDR display. The tone mapping feature seems to have no effect. In another issue here, I posted a sample video shot in HLG with a bt2020 colorspace, and that is very overexposed in iina. 

https://github.com/iina/iina/issues/4523#issuecomment-2797528227

I have not played around with mpv to debug. The whole mpv project smells of "oss-itis" to me: stuff the Linux nerds don't care about is pushed to the side. I've seen your comments about HDR being "bleeding edge" and that is why it's not well supported. I disagree. The issue is a general lack of interest and knowledge of the broader color management topic in the Linux world. That world just doesn't care enough, and hardware support is so terrible in Linux, a lot of them can't even test that stuff.

**Comment by low-batt** [comment]
Good points about the Linux world. I still deem HDR as bleeding edge due to the state of HDR when it comes to still pictures. Things are improving. But I don't think I can use macOS to take a true screenshot of the screen when playing a HDR video. If I take a JPEG XL screenshot of a HDR video using IINA I don't think GitHub will let me upload it and have it display for browsers that can display HDR pictures. That kind of issue.

If you browse through mpv issues you will see that they are serious about color. There are many issues about it and some have a huge number of comments. However a lot of the recent work, including better Dolby Vision support has only gone into GPU Next.

**Comment by LeoNatan** [comment]
PNG has full support for color profiles, so there is no technical limitation why the resulting PNG has a P3 embedded color profile, rather than the display's "X"DR profile.

JXL isn't supported in Chrome, due to ridiculous Google attempt to push AVIF, an inferior codec. 

Testing what formats are supported on GH, it seems only PNG is supported. For the others I tested, I get `File types not allowed: .avif, .jxl, .tif`

![Image](https://github.com/user-attachments/assets/3a003cc9-71fd-4df2-8016-47700ded9aa2)

It's a silly artificial limit by GitHub.

**Comment by LeoNatan** [comment]
But Safari/WebKit won't render HDR in the above PNG 🤣

Firefox is not much better:

<img width="1193" alt="Image" src="https://github.com/user-attachments/assets/3636bc06-ebd8-4a39-b388-0143ed5c1e5a" />
