### ISSUE TITLE
App sliders are broken in Sonoma 14.2 beta 4 (macOS issue, no fix needed in IINA)

### ISSUE THREAD

**Issue by waydabber** [iina/iina#4703]
**System and IINA version:**

- macOS Sonoma 14.2 beta 4
- IINA 1.3.3

**Expected behavior:**

The fill indicator in the Sliders are in sync with the knob and properly updated when the knob is being moved.

**Actual behavior:**

Sliders are not updated properly when moving the knob.

**Steps to reproduce:**

Use any slider in the app and observe sliders not drawing properly when interacting with them.

**How often does this happen?**

**This is not an IINA issue** but a general bug in macOS 14.2 beta 4 affecting various other apps as well. Just opened this issue so others who experience the same can be reassured it's not IINA. Apple will hopefully provide a fix in the next beta. :)

**Comment by low-batt** [comment]
Thank you for reporting this.

This is not the only IINA Sonoma related issue. Click on the `macOS 14 Sonoma` label to see the others. Those issues are with the released version of Sonoma.

I have found posts reporting other applications are experiencing the problem with tool tips not displaying. We are hoping that is fixed in 14.2.

I have not been able to find posts reporting the problem with the clearing of the `Open Recent` list. That only happens when IINA is built using Xcode 15.

I sure hope these issues disappear with the release of 14.2.

**Comment by waydabber** [comment]
Yeah, Sonoma has various issues for sure. I am struggling with these in my app as well. :) XCode 15 has issues too (worst is, my XCode 15 installation tends to mix up source files in the editor randomly -!!- I can't seem to figure out how to fix that - super annoying 😡 especially as on my other Mac this does not happen).

**Comment by derpyjoystick** [comment]
As others have said, this affects macOS across the board. Every slider across the OS is experiencing the lack of visual feedback when manipulating the element.

**Comment by low-batt** [comment]
I noticed @waydabber has closed the issue for this problem in the [BetterDisplay](https://github.com/waydabber/BetterDisplay) repository reporting it has been fixed in [macOS Sonoma 14.2 RC](https://developer.apple.com/documentation/macos-release-notes/macos-14_2-release-notes). I have not heard if [Xcode 15.1 RC](https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-15_1-release-notes) has solved the above mentioned editor defect.

I'm thinking IINA issue #4705 which occurs with the latest released version of macOS Sonoma (14.1.2) is another [NSSlider](https://developer.apple.com/documentation/appkit/nsslider) defect. I'm hoping that one will not reproduce in the 14.2 version that is released.

Once 14.2 is released I will confirm these slider issues are fixed and close them.

**Comment by low-batt** [comment]
I've upgraded to macOS 14.2 and I'm not seeing a problem with the slider fill indicator, so I am going to close this issue.

The other slider problem, #4705, is due to a workaround in the IINA code that is no longer needed as it appears Apple has fixed `NSSlider`. I've just posted a PR for that issue.

**Comment by LightningRocks** [comment]
I am still having the issue in macOS 14.3 beta with specifically IINA 1.3.3. It does not seem to affect other applications such as Apple Music or Discord. It did not get resolved with the latest pushed Nightly build either

**Comment by waydabber** [comment]
Yes, the first 14.3 beta has the same bug (again), will probably be fixed by the next beta.

**Comment by derpyjoystick** [comment]
Fixed in 14.3 beta 2.

**Comment by waydabber** [comment]
Hooray! :)

**Comment by low-batt** [comment]
IINA 1.3.4 has a fix for the other slider problem that showed up in Sonoma where the knobs showing the A-B loop points were duplicated and in the wrong place.

Disturbing to hear about bugs reappearing. This is not the only case of that happening. It is suggestive of a lack of coordination between software engineers and trouble with resolving merge conflicts in the source code.
