### ISSUE TITLE
Chinese subtitles are garbled on macOS 15.0

### ISSUE THREAD

**Issue by WanliZhong** [iina/iina#5176]
I upgraded my system version to macOS 15.0 today, and found the Chinese characters are garbled but correct on macOS 14
**System and IINA version:**

- macOS 15.0
- IINA 1.3.5

**Expected behavior:**
Show Chinese characters correctly

**Actual behavior:**
Show nothing for Chinese, but English is fine. macOS 14 is also fine.

![Screenshot 2024-09-17 at 22 43 04](https://github.com/user-attachments/assets/51eb314a-6454-46e2-9e32-4afdf1a9833e)

**Steps to reproduce:**
Subtitle file (remove the `.txt` suffix): 
[Stranger.Things.S02E01.1080p.BluRay.x265-RARBG.ass.txt](https://github.com/user-attachments/files/17030088/Stranger.Things.S02E01.1080p.BluRay.x265-RARBG.ass.txt)

**Comment by low-batt** [comment]
This looks like a duplicate of issue #5164. See that issue for details. Users reported that after updating to the macOS 15.1 Beta subtitles were working again. Disappointing to hear that Apple failed to fix this for the 15.0 release.

**Comment by WanliZhong** [comment]
OK, Thanks. I will wait for the update from apple

**Comment by low-batt** [comment]
In [this comment](https://github.com/iina/iina/issues/5164#issuecomment-2328450355) on issue #5164 @the-eric-kwok indicated:
> Workaround: Change the subtitle font to a Chinese font other than PingFang, and it will render normally.

**Comment by FR13NDS-wolf** [comment]
Same issue. but after I upgrate to macOS 15.1 Beta, this problem still exist🥲.
I guess the problem is blamed on Apple. 
<img width="1254" alt="image" src="https://github.com/user-attachments/assets/3440a3a0-5572-4934-a067-68cd1203d0d9">

**Comment by low-batt** [comment]
The expectation that this is something that is fixed in the macOS 15.1 Beta is based on user reports. As it is not working for you it is time to take a closer look.

There are many [Subtitle formats](https://en.wikipedia.org/wiki/Subtitles#Subtitle_formats). What kind of subtitle format is being used? Click on `Inspector` under the `Window` menu. In the `Inspector` window click on the `Tracks` tab. Select the problematic subtitle track. What is listed for `Codec`?
![inspector](https://github.com/user-attachments/assets/32c75b4b-d4be-4372-aed5-32b33c496656)


Is this an external subtitle file? If so, can you attach the subtitle file to this issue?

Do we know what font is being used? Does [Font Book](https://support.apple.com/guide/font-book/install-and-validate-fonts-fntbk1000/mac) show the font is present on the Mac?

**Comment by FR13NDS-wolf** [comment]
Thanks for these tips, I finally solved the issue.
The Problem is that **Fonts are missing.** 
(subtitle formats in iina is working ok. 

Now let's step by step to solve it.

1. Check the subtitle use what kind of font.
<img width="658" alt="image" src="https://github.com/user-attachments/assets/6030566f-f4aa-4cfe-965a-4fefb53b5708">
<img width="350" alt="image" src="https://github.com/user-attachments/assets/5a566353-b979-4141-a55a-16c0fd62ee1c">
<img width="336" alt="image" src="https://github.com/user-attachments/assets/df3577eb-7b51-4be7-81a2-a97a3538585e">


2. Go to  Font Book search that font if it not exist in your mac.
3. Download the missing fonts and install them.
4. (optional restart mac
 
I just download two kind of Fonts  the questions have disappear. I list them:
microsoft YaHei:  https://github.com/BronyaCat/Win-Fonts-For-Mac  
思源黑体: https://github.com/adobe-fonts/source-han-sans

<img width="1454" alt="image" src="https://github.com/user-attachments/assets/ea6d7b41-df79-4db9-bde6-8152524feb2c">

Respect

**Comment by WanliZhong** [comment]
Maybe on old macOS, the default font will be used when font is missing? Now on macOS, missing font will not have this behaviour. My iPadOS 18 also have this problem with other players.

**Comment by RunpuWei** [comment]
I encountered this problem too, and I temporarily solved the BUG by setting up a custom font.

**Comment by low-batt** [comment]
The `Stranger.Things.S02E01.1080p.BluRay.x265-RARBG.ass` subtitle file provided by @WanliZhong uses the font `方正黑体_GBK`:
```text
Style: Default,方正黑体_GBK,20,&H00FFFFFF,&HF0000000,&H00000000,&H32000000,0,0,0,0,100,100,0,0,1,2,1,2,5,5,2,134
```

This subtitle is rendered correctly for me using IINA 1.3.5 under macOS Ventura 13.6.9. Checking the mpv log file shows use of the `PingFang` font:
```text
[   6.988][i][sub/ass] fontselect: Using default font family: (方正黑体_GBK, 400, 0) -> /System/Library/Fonts/Helvetica.ttc, -1, Helvetica
[   6.988][v][sub/ass] fontselect: (方正黑体_GBK, 400, 0) -> /System/Library/Fonts/Helvetica.ttc, -1, Helvetica
[   6.989][i][sub/ass] fontselect: Using default font family: (方正黑体_GBK, 700, 0) -> /System/Library/Fonts/Helvetica.ttc, -1, Helvetica-Bold
[   6.989][v][sub/ass] fontselect: (方正黑体_GBK, 700, 0) -> /System/Library/Fonts/Helvetica.ttc, -1, Helvetica-Bold
[   6.989][i][sub/ass] fontselect: Using default font family: (方正粗倩_GBK, 700, 0) -> /System/Library/Fonts/Helvetica.ttc, -1, Helvetica-Bold
[   6.989][v][sub/ass] fontselect: (方正粗倩_GBK, 700, 0) -> /System/Library/Fonts/Helvetica.ttc, -1, Helvetica-Bold
[   6.989][v][sub/ass] Glyph 0x5BBE not found, selecting one more font for (方正粗倩_GBK, 700, 0)
[   7.002][v][sub/ass] fontselect: (方正粗倩_GBK, 700, 0) -> /System/Library/Fonts/PingFang.ttc, -1, PingFangSC-Semibold
```

In the Apple Developer Forums post [PingFang.ttc font file is missing in iOS 18.0](https://forums.developer.apple.com/forums/thread/758189) a developer reports:
> I'm an iOS developer, and I've been testing our app in iOS 18.0 Beta. I noticed that there's a problem with the font rendering, and after troubleshooting, I've found out that it's caused by the removal of the PingFang.ttc font in 18.0. I would like to ask the reason for removing this font file and which font should be used to display Chinese in the future?

An Apple Frameworks Engineer responds saying:
> PingFang.ttc is no longer in /System/Library/Fonts/Core. iOS 18 has a new Chinese UI font.

See the forum post for full details. This confirms an intentional Apple change is behind this problem. I wish that response would have said what the new font is.

**Comment by low-batt** [comment]
I finally had time to upgrade to macOS Sequoia 15.0 and this problem reproduced for me.

The log clip posted above indicated that because the font `方正粗倩_GBK` is not available, on macOS Sonoma font fallback selected `PingFangSC-Semibold`. On Sonoma [Font Book](https://support.apple.com/guide/font-book/welcome/mac) shows:
![font-book-sonoma](https://github.com/user-attachments/assets/2b8c516f-de00-48c8-8363-5e7d34e14f8a)

After the upgrade to Sequoia [Font Book](https://support.apple.com/guide/font-book/welcome/mac) shows:
![font-book-sequoia](https://github.com/user-attachments/assets/09202a80-1d97-4dbf-b8c3-9bf31c2ae1a0)

The icons are dimmed because the PingFang fonts are not preinstalled, they have to be downloaded. Hover over the `PingFang SC` icon and click on the small circled down arrow that appears to download and install the fonts.

In `Font Book` if you click on `Show Info Pane` under the `View` menu a side bar appears. If you click on the `Details` disclosure triangle `Font Book` shows a bunch of information about the font. In Sequoia `No`  is shown under `System Font`. I forgot to check this information before upgrading from Sonoma, but on my MacBook running Ventura `Font BooK` shows `Yes` for `System Font`.

Apparently Apple changed the `PingFang` font from being a preinstalled system font in earlier macOS releases to a font that is not installed and must be downloaded.

**Comment by WanliZhong** [comment]
@low-batt Thanks, I reinstalled PingFang family fonts in FontBook to make it normal.

**Comment by bobishappy** [comment]
> I finally had time to upgrade to macOS Sequoia 15.0 and this problem reproduced for me.
> 
> The log clip posted above indicated that because the font `方正粗倩_GBK` is not available, on macOS Sonoma font fallback selected `PingFangSC-Semibold`. On Sonoma [Font Book](https://support.apple.com/guide/font-book/welcome/mac) shows: ![font-book-sonoma](https://private-user-images.githubusercontent.com/86170219/371725038-2b8c516f-de00-48c8-8363-5e7d34e14f8a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MjY5MTIsIm5iZiI6MTcyNzgyNjYxMiwicGF0aCI6Ii84NjE3MDIxOS8zNzE3MjUwMzgtMmI4YzUxNmYtZGUwMC00OGM4LTgzNjMtNWU3ZDM0ZTE0ZjhhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDIzNTAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNmNjNmZiOTBkZmQ3ZTA1N2JiZDNkNGY0MTE0NGI0ZjU5OTA3YzFkMmQxMGY0YzI5YmFmZDgyYThhMTIxMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lDAwLhdYeh7L7I8Zjm9iRrO9ZCEtUak-Su6YoEO8jFw)
> 
> After the upgrade to Sequoia [Font Book](https://support.apple.com/guide/font-book/welcome/mac) shows: ![font-book-sequoia](https://private-user-images.githubusercontent.com/86170219/371725065-09202a80-1d97-4dbf-b8c3-9bf31c2ae1a0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MjY5MTIsIm5iZiI6MTcyNzgyNjYxMiwicGF0aCI6Ii84NjE3MDIxOS8zNzE3MjUwNjUtMDkyMDJhODAtMWQ5Ny00ZGJmLWI4YzMtOWJmMzFjMmFlMWEwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDIzNTAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3MmI1OWM0ODVhMjdlYTgzZWY1NTZhNjA0YjJhOTMwNzliNjg1ZTlhMDJjNTJiMjIzZTM2MjBjNDMxMjAxYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RzDGzRE4vWseEkyXknpiFxojIy-h8owI5fx12RbxkaI)
> 
> The icons are dimmed because the PingFang fonts are not preinstalled, they have to be downloaded. Hover over the `PingFang SC` icon and click on the small circled down arrow that appears to download and install the fonts.
> 
> In `Font Book` if you click on `Show Info Pane` under the `View` menu a side bar appears. If you click on the `Details` disclosure triangle `Font Book` shows a bunch of information about the font. In Sequoia `No` is shown under `System Font`. I forgot to check this information before upgrading from Sonoma, but on my MacBook running Ventura `Font BooK` shows `Yes` for `System Font`.
> 
> Apparently Apple changed the `PingFang` font from being a preinstalled system font in earlier macOS releases to a font that is not installed and must be downloaded.

Thank you so much. This solution works on my M2 Mac. I updated my Mac from 15.0 to 15.1 beta 2, which did not solve the problem initially, however installing the PingFang font does make it work.

**Comment by laloe74** [comment]
> I finally had time to upgrade to macOS Sequoia 15.0 and this problem reproduced for me.
> 
> The log clip posted above indicated that because the font `方正粗倩_GBK` is not available, on macOS Sonoma font fallback selected `PingFangSC-Semibold`. On Sonoma [Font Book](https://support.apple.com/guide/font-book/welcome/mac) shows: ![font-book-sonoma](https://private-user-images.githubusercontent.com/86170219/371725038-2b8c516f-de00-48c8-8363-5e7d34e14f8a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMjg5NzgsIm5iZiI6MTczMjAyODY3OCwicGF0aCI6Ii84NjE3MDIxOS8zNzE3MjUwMzgtMmI4YzUxNmYtZGUwMC00OGM4LTgzNjMtNWU3ZDM0ZTE0ZjhhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDE1MDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2YzlmMzQwZTg0MTNiZjBkZTM4NGIzMzlhM2RhNzhmNjIzOTU3YmU2YzE4OTRlZDNjYmFkNjNjM2E2MWQzZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PjLqYjYKjmLW2jlqeTlHWv9VwW1P9sXDrDl3p569QOk)
> 
> After the upgrade to Sequoia [Font Book](https://support.apple.com/guide/font-book/welcome/mac) shows: ![font-book-sequoia](https://private-user-images.githubusercontent.com/86170219/371725065-09202a80-1d97-4dbf-b8c3-9bf31c2ae1a0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMjg5NzgsIm5iZiI6MTczMjAyODY3OCwicGF0aCI6Ii84NjE3MDIxOS8zNzE3MjUwNjUtMDkyMDJhODAtMWQ5Ny00ZGJmLWI4YzMtOWJmMzFjMmFlMWEwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDE1MDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlNTlmMmU1MGRmN2E3OWE0Y2M4YjIzOTc2MzNkNTFkZGQwOTYyNGVlMzQ4MjYxNWEwZjhkMWVjNGJmODcyNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.U_T8u8hFC3270QBel02_XNmsZvofvsv_W9PPZYlhLmk)
> 
> The icons are dimmed because the PingFang fonts are not preinstalled, they have to be downloaded. Hover over the `PingFang SC` icon and click on the small circled down arrow that appears to download and install the fonts.
> 
> In `Font Book` if you click on `Show Info Pane` under the `View` menu a side bar appears. If you click on the `Details` disclosure triangle `Font Book` shows a bunch of information about the font. In Sequoia `No` is shown under `System Font`. I forgot to check this information before upgrading from Sonoma, but on my MacBook running Ventura `Font BooK` shows `Yes` for `System Font`.
> 
> Apparently Apple changed the `PingFang` font from being a preinstalled system font in earlier macOS releases to a font that is not installed and must be downloaded.

Thank you!!!!!!!!!!!!!!!

**Comment by qixiaobo** [comment]
https://github.com/lyswhut/lx-music-desktop/issues/2076 same problems here!

**Comment by low-batt** [comment]
Hi @qixiaobo,

In case you missed it, [this comment](https://github.com/iina/iina/issues/5176#issuecomment-2380401632) above provides instructions for downloading the PingFang fonts that no longer come pre-installed. I still have not found any explanation from Apple as to why they made this change.

**Comment by birdyun2544** [comment]
> Thanks for these tips, I finally solved the issue. The Problem is that **Fonts are missing.** (subtitle formats in iina is working ok.
> 
> Now let's step by step to solve it.
> 
> 1. Check the subtitle use what kind of font.
> 
> <img alt="image" width="658" src="https://private-user-images.githubusercontent.com/52058370/368842659-6030566f-f4aa-4cfe-965a-4fefb53b5708.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDM3Njk5OTEsIm5iZiI6MTc0Mzc2OTY5MSwicGF0aCI6Ii81MjA1ODM3MC8zNjg4NDI2NTktNjAzMDU2NmYtZjRhYS00Y2ZlLTk2NWEtNGZlZmI1M2I1NzA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDA0VDEyMjgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMGVmNzM1ZjdmNDg3MjU2OTA4MzYwODgxMGY2NzAyZDljOGQ2YTJiOWVjMzU5NzgxNmMxYWQ4NjMxZDNkY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EdCLiPOhUchCJsbaH-MHq2nMq8Z8z8uQchTQv9VNjUs"> <img alt="image" width="350" src="https://private-user-images.githubusercontent.com/52058370/368843192-5a566353-b979-4141-a55a-16c0fd62ee1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDM3Njk5OTEsIm5iZiI6MTc0Mzc2OTY5MSwicGF0aCI6Ii81MjA1ODM3MC8zNjg4NDMxOTItNWE1NjYzNTMtYjk3OS00MTQxLWE1NWEtMTZjMGZkNjJlZTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDA0VDEyMjgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMDc2Zjk4OTQ5YTQwYzI0ODY1NmMxMTlkYzY4YzQwNTM3OWVjOWIxZmEzNjFlM2EyM2ZmMDhlNzljNmNkYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._3buD_Fmz1HjONtRm4BaiBzdhIdlur2lgVu8cdqFsNQ"> <img alt="image" width="336" src="https://private-user-images.githubusercontent.com/52058370/368843266-df3577eb-7b51-4be7-81a2-a97a3538585e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDM3Njk5OTEsIm5iZiI6MTc0Mzc2OTY5MSwicGF0aCI6Ii81MjA1ODM3MC8zNjg4NDMyNjYtZGYzNTc3ZWItN2I1MS00YmU3LTgxYTItYTk3YTM1Mzg1ODVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDA0VDEyMjgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwZmE0ZTYwYzNkMmUxZjIzZGEwYTdkYWI5NDU5ODg4OGQ0ZTgyNWZhYjMwMzhkZDU2NjFmMmRjODhhMjhiYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.O_-Hwd3D4-B3mGsqg28wWy2C67f5fW4mOy5y0kLuieg">
> 2. Go to  Font Book search that font if it not exist in your mac.
> 3. Download the missing fonts and install them.
> 4. (optional restart mac
> 
> I just download two kind of Fonts the questions have disappear. I list them: microsoft YaHei: https://github.com/BronyaCat/Win-Fonts-For-Mac 思源黑体: https://github.com/adobe-fonts/source-han-sans
> 
> <img alt="image" width="1454" src="https://private-user-images.githubusercontent.com/52058370/368842459-ea6d7b41-df79-4db9-bde6-8152524feb2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDM3Njk5OTEsIm5iZiI6MTc0Mzc2OTY5MSwicGF0aCI6Ii81MjA1ODM3MC8zNjg4NDI0NTktZWE2ZDdiNDEtZGY3OS00ZGI5LWJkZTYtODE1MjUyNGZlYjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDA0VDEyMjgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMmU1Y2VmMTAyNWYwYTczNzM4ZGIxMzViYjJmOGExMDQzMWY4NjI1YzAyZDkwNTE2MzE3OWMwZjBmNjQ1NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.O9M4gcYAFYUtCVL3HKN00_5e07cPysZGevlqRK6uCSg">
> Respect

I fixed the issue by your method ,thanks!

**Comment by alienmeat** [comment]
Hi guys, I am using a srt file as my subtitle and it doesnt contain any font, The chinese charcters are still showing as blocks. Anyone has any idea?

**Comment by low-batt** [comment]
For audio/video and subtitle rendering IINA is using a library from the [mpv project](https://github.com/mpv-player/mpv).  The font for text based subtitles like `.srt` files is controlled by the mpv [sub-font](https://mpv.io/manual/stable/#options-sub-font) option:
> **--sub-font=\<name>**
>    Specify font to use for subtitles that do not themselves specify a particular font. The default is `sans-serif`.

And if we open IINA's settings to the `Subtitle` tab the `Text Subtitles` section confirms the selected font is `sans-serif` (unless you changed it):

![Image](https://github.com/user-attachments/assets/4612b8f2-363c-4174-a803-73dac083dfa7)

Searching around the net I found a post that indicates the default Sans-Serif font for Chinese is: **PingFang**. This is the font that Apple, for reasons unknown, no longer installs by default. You must now use [Font Book](https://support.apple.com/guide/font-book/welcome/mac) to download these fonts.

Have you followed the instructions in the comment [above](https://github.com/iina/iina/issues/5176#issuecomment-2380401632) that show how to download the PingFang fonts?

**Comment by alienmeat** [comment]
> For audio/video and subtitle rendering IINA is using a library from the [mpv project](https://github.com/mpv-player/mpv). The font for text based subtitles like `.srt` files is controlled by the mpv [sub-font](https://mpv.io/manual/stable/#options-sub-font) option:
> 
> > **--sub-font=<name>**
> > Specify font to use for subtitles that do not themselves specify a particular font. The default is `sans-serif`.
> 
> And if we open IINA's settings to the `Subtitle` tab the `Text Subtitles` section confirms the selected font is `sans-serif` (unless you changed it):
> 
> ![Image](https://github.com/user-attachments/assets/4612b8f2-363c-4174-a803-73dac083dfa7)
> 
> Searching around the net I found a post that indicates the default Sans-Serif font for Chinese is: **PingFang**. This is the font that Apple, for reasons unknown, no longer installs by default. You must now use [Font Book](https://support.apple.com/guide/font-book/welcome/mac) to download these fonts.
> 
> Have you followed the instructions in the comment [above](https://github.com/iina/iina/issues/5176#issuecomment-2380401632) that show how to download the PingFang fonts?

Thanks! I just downloaded the font and it is solved!

**Comment by 3kh0** [comment]
I am on the latest macos beta (liquid ass) and it seemed that adding simplified Chinese as a language and changing the font settings under subtitles was enough to fix the issue! 

1. Check the font book to see what fonts you have installed for Chinese
2. If none show, try adding the Chinese language to your system
3. Go to IINA, and on the top bar hit "Subtitles" and "Font"
4. Select the variant that you have installed

**Comment by birdyun2544** [comment]
thank you,that problem has been solved






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2025年10月30日(星期四) 上午8:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [iina/iina] Chinese subtitles are garbled on macOS 15.0 (Issue #5176)












3kh0 left a comment (iina/iina#5176)
 
I am on the latest macos beta (liquid ass) and it seemed that adding simplified Chinese as a language and changing the font settings under subtitles was enough to fix the issue!
  
Check the font book to see what fonts you have installed for Chinese
 
If none show, try adding the Chinese language to your system
 
Go to IINA, and on the top bar hit "Subtitles" and "Font"
 
Select the variant that you have installed
