### ISSUE TITLE
Find online subtitles does nothing.

### ISSUE THREAD

**Issue by Jalbert8120** [iina/iina#5261]
### IINA Version

1.3.5 Build 141

### Release Channel

Release

### macOS Version

15.0.1 (24A348)

### Steps to Reproduce

- clicking on" find online subtitles"

### Expected Behavior

Finds online subtitles

### Actual Behavior

Does absolutely nothing. Shows nothing.

### How often can you reproduce the issue

Every time for months and months now

### Required Actions

- [X] I tried my best to search from the existing issues (including closed issues) and didn't find duplicated issues.

### Optional Actions

- [X] I tested with the Nightly build and confirmed the issue is not fixed.
- [ ] I tested with the latest version of mpv and confirmed mpv doesn't have this issue.

**Comment by low-batt** [comment]
Thanks for reporting this!

My best guess is that this is due to the problem discussed in issue #4422. Except that problem is fixed in the development version of IINA, so the Nightly built should have worked.

Check the `Enable OSD` setting as discussed in [this comment](https://github.com/iina/iina/issues/4422#issuecomment-1553881692). If that is unchecked then test if checking it causes finding online subtitles to start working. If so, then this is issue #4422.

If that does not explain the problem then I'm at a loss as to what is causing this. We can see if the log files provide a clue as to what is going wrong. See the FAQ [How to collect log files when reporting an issue?](https://github.com/iina/iina/wiki/FAQ#how-to-collect-log-files-when-reporting-an-issue).

If this is issue #4422, that problem will be fixed in the next release of IINA. We are currently in final testing in preparation for a Beta release.

**Comment by Jalbert8120** [comment]
This still doesn't work. I've been updating to newest versions every time. Haven't been able to find subtitles in over a year at this point.

**Comment by low-batt** [comment]
Open Subtitles shutdown free access to [opensubtitles.org](https://www.opensubtitles.org/) forcing IINA to switch to the new [opensubtitles.com](https://www.opensubtitles.com/) site. This required a major rewrite of the code that accesses Open Subtitles. There certainly could be something wrong with the new code.

As a part of that rewrite extensive logging was added. If something is going wrong there should be an indication in the log file. To tell what is happening I need an IINA log file captured after you clicked on `Find Online Subtitles from opensubtitles.com`. Click on `Log Viewer`. In the `Log Viewer` window click on `Save as…`. Save the log file and then drag and drop it to the `Add a comment` section below. Post a comment with the log file and I will take a look.

If you are using an Open Subtitles account then you **must** migrate the account as discussed in [this comment](https://github.com/iina/iina/issues/3920#issuecomment-1774181503). This is an Open Subtitles requirement.

Does "updating to newest versions" refer to the nightly development builds found [here](https://iina.io/nightly/)?

In IINA's settings on the `UI` tab in the `On Screen Display` section is the `Enable OSD` setting checked?

**Comment by Jalbert8120** [comment]
[iina.log](https://github.com/user-attachments/files/18225725/iina.log)


I am logged into an opensubtitles.com account.


By "updating to newest versions" I mean I have both the update boxes checked in settings.

<img width="932" alt="Screenshot 2024-12-22 at 10 08 45 PM" src="https://github.com/user-attachments/assets/6e4ee1b7-4e1f-46e5-b1cd-c1e9b96b2e14" />


Enable OSD was not checked. I just checked it, restarted, and tried finding subtitles again. No change.

**Comment by low-batt** [comment]
> By "updating to newest versions" I mean I have both the update boxes checked in settings.

Ah. We have been adding FAQs that explain some of the questions asked in the issue template. I've been thinking we need to add one that explains this question:

> I tested with the Nightly build and confirmed the issue is not fixed.

That question is referring to builds of the development version of IINA, not official releases which is what the update settings in IINA control.

I was confused because the development version of IINA has a fix to a problem where if the `Enable OSD` setting is not checked you get exactly the behavior you are reporting. In IINA 1.3.5 you must have that setting checked to use the feature for downloading subtitles.

That should have been what was causing the problem. So I'm confused as to why after enabling that setting you are still not seeing anything.

The log file seems to be truncated? I don't even see log messages showing a video file was opened? Please try collecting logs again. This time follow the instructions in this FAQ [How to collect log files when reporting an issue?](https://github.com/iina/iina/wiki/FAQ#how-to-collect-log-files-when-reporting-an-issue).

Be sure to restart IINA after enabling logging. Start the video playing. Then click on `Find Online Subtitles from opensubtitles.com`. Wait for a short while. If nothing happens quit IINA and then obtain the log files as discussed in that FAQ.

**Comment by Jalbert8120** [comment]
Is this better?

[iina.log](https://github.com/user-attachments/files/18227977/iina.log)

Am I supposed to be saving more than just this top file?

<img width="720" alt="Screenshot 2024-12-23 at 1 48 05 AM" src="https://github.com/user-attachments/assets/6d6a21de-26a6-4dfa-bf01-dd55e30cc8a6" />

**Comment by low-batt** [comment]
In IINA's settings on the `Advanced` tab do you have `Use mpv's OSD` checked? If so, uncheck it, restart IINA and test again. It has been a while since I worked on this and I forgot that other aspect of the problem. If  `Use mpv's OSD` is checked it disables IINA's OSD.

With the next version of IINA you can use mpv's OSD and still be able to download subtitles.

By the way, while testing this the subtitles feature failed once for me. From a quick look OpenSubtitles reported they were overloaded. First time I've seen this. IINA was supposed to be able to handle this. Instead that feature hung up. I will be looking into that.

**Comment by Jalbert8120** [comment]
That did it. It's been a while since I set that, but it looks like I it that checked so that it would automatically adjust the video brightness and saturation each time I open a file. Is there any way to do that without using that option?
<img width="985" alt="Screenshot 2024-12-27 at 10 01 22 AM" src="https://github.com/user-attachments/assets/dab24516-686c-44b4-b242-c3e16fae24a5" />

**Comment by low-batt** [comment]
I think this UI needs to be improved to make it clear that these settings are all separate:
- `Use mpv's OSD`
- `Additional mpv options`
- `Use config directory`

The `brightness` and `saturation` options will be set regardless of whether  `Use mpv's OSD` or `Use config directory` are enabled. If all you need is for the `brightness` and `saturation` options to be set you can uncheck both `Use mpv's OSD` and `Use config directory` and they will still be set by IINA.

The `Use mpv's OSD` is about replacing IINA's OSD with mpv's. Some users want to do this because as can be seen in the [OSD](https://mpv.io/manual/stable/#osd) section of mpv's manual there are many options available to customize the mpv OSD. The IINA defect was that IINA's OSD should still be displayed when being used for the UI of the download subtitles feature and the screenshot preview feature. This defect has been corrected and the fix will be in the next release of IINA.

The option/value pairs in `Additional mpv options` are applied by IINA when configuring mpv. In some cases IINA detects that you have supplied a value for a mpv option that normally IINA would set and avoids overwriting your value.

When `Use config directory` is enabled IINA will instruct mpv to load a mpv configuration file. This has the downside of hiding from IINA that you are setting options. However mpv config files have features such as [Conditional auto profiles](https://mpv.io/manual/stable/#conditional-auto-profiles) and therefore may be needed for advanced configuration.

**Comment by Jalbert8120** [comment]
Now I'm having a problem where MKV files just won't show subtitles at all. Don't know if it's related. It still shows that a subtitle track is selected in the upper left-hand corner, and I can still find online subtitles and load those, but nothing appears on the screen..Other file types (AVI, MP4) work fine.

**Comment by low-batt** [comment]
That sounds like a different problem. Better to open a new issue for it.

Subtitles can be hidden. Users who configure their key bindings to use mpv's bindings instead of IINA's have accidentally typed `V`, which is bound to `Cycle Subtitle visibility`, and hidden subtitles. If the IINA setting `Resume last playback position` is enabled that setting will also be remembered, so restarting IINA will not restore subtitles. To clear this you have to type `V` again, restoring subtitle visibility. This is only an issue when using mpv's key bindings.

If that is not it, please open a new issue with log files and I will see what the logs say is happening.

**Comment by low-batt** [comment]
This was fixed in IINA 1.4.0.

Closing this as find online subtitles now works even if the mpv OSD is being used.
