### ISSUE TITLE
Update "Date last opened" Finder metadata

### ISSUE THREAD

**Issue by patrickrushton** [iina/iina#579]
When a file is opened, the "Date last opened" Finder data should be updated. At the moment, this only happens when the file is opened from Finder (e.g. double-click). It could also be updated when

- file is reached in a playlist
- file is dragged onto the player window
- file opened via File > Open dialog

**Comment by fmaluse** [comment]
I think it makes sense that this data should be updated regardless of from where the file is opened. It would make it easier to keep track of which media has been viewed. I'd very much like to see this implemented!

**Comment by IsaacInsoll** [comment]
I'd love this too

**Comment by ccj242** [comment]
Me three. Would love this.

**Comment by smoyn** [comment]
Implementing this would make the Finder an excellent video manager rather just a good one. I have not come across any player that implements this feature. You could be the first.

**Comment by low-batt** [comment]
PR #3707 with support for this feature has been merged into the develop branch.

**Comment by low-batt** [comment]
Closing. Fixed in IINA 1.3.0.

**Comment by smoyn** [comment]
Like the new v3 build 132. There is bad news and good news:

The Bad:
Finder still NOT updating videos opened by Iina playlist mode on my machine running Mojave. Only videos manually opened from the Finder  update "date last opened" in Finder. Same as before the update. Playlist mode in Iina does work in Iina history but never updates the Finder.

The good:
"Date last opened" in Finder WILL work now for files opened in Iina playlist mode, IF the User has a Saved (spotlight) Search  placed in the sidebar. That is new, it didn't work in previous versions of Iina. 
The parameters of my search are simple: Kind is: any or movie, (any includes folders containing the movies). 
(Last Opened Date) is (within last X days weeks etc)

So the work around is good enough for me, still would be nice to see it in the Finder too. One other note is I started to use Iina History window as the controller for serialized files, and found it works as well as the Saved search results without having to switch back and forth between Iina and the Finder. The issue with Iina History window is the tiny ass font and no way to change it. All in all I'm happy with the way Iina works following the updates. Thanks
