### ISSUE TITLE
Expand file open customization settings

### ISSUE THREAD

**Issue by Cykelero** [iina/iina#5865]
The way IINA handle opening (multiple) files from the Finder has changed a bit this year, and some people have responded with requests for more options. This PR aims to rework IINA's open settings just enough to support all the needs that have been expressed.

# Proposal

We would replace this setting:

- [ ] Always open media in new window

With these:

- [X] Allow multiple player windows
	- [X] Group media in playlist when opening multiple files at once
	- [ ] Allow opening the same file in multiple windows

The two nested settings would only be enabled if the parent setting is checked. The default values, as shown, would match standard macOS behavior.

I'm happy to implement this, but wanted to ask for approval first!

# Context

- #5071 made it so that selecting multiple files in the Finder, and opening them all at once, doesn't create a playlist anymore, when “Always open media in new window” is selected. Instead, it opens each in its own window.
	- This matches system behavior, and likely matches most people's expectations
	- You can still create playlists by unchecking the setting; or by dragging files on an existing player
	- But, that means it's now harder to decide on-the-fly between opening a group of files in a single window, or multiple (before, you could make that choice by either opening each file separately, or opening one big selection all at once)
		- Requests: https://github.com/iina/iina/issues/5574#issuecomment-3522807735, https://github.com/iina/iina/issues/5574#issuecomment-3621579409, https://github.com/iina/iina/issues/5574#issuecomment-3693760584, https://github.com/iina/iina/issues/5488#issuecomment-3313495250
- That same PR also made it impossible to open the same file in multiple windows.
	- This matches system behavior, and likely matches most people's expectations
	- But, that means you can no longer open two windows of the same file to e.g. compare different times of the video
		- Request: #5689
	- This change has already been completely reverted in #5689. I proposed instead adding a setting for it in #5762. That PR would be replaced by the changes proposed here.

So, since no single behavior will satisfy everyone, it could be a good idea to find the right set of settings to add. These are the small, easiest-to-understand set I've been able to come up with.

**Comment by low-batt** [comment]
@Cykelero Thank you for looking into this! Glad you asked for advice in advance.

I'm a _junior_ IINA developer. We need to hear from the senior developers. I will see if I can get their attention. As I am about to explain, at the moment it is a bad time to add functionality. However I think we need to make an exception in this case.

The next release was supposed to be IINA 1.5.0 which includes upgrading mpv, FFmpeg and other dependencies. That work ran into trouble supporting macOS Catalina as well as other problems. As a result a decision was made switch to working on an IINA 1.4.2 release dedicated to bug fixes. That work is also taking too long as additional problems introduced by Apple in macOS Tahoe have been discovered.

I'm thinking the changes proposed in this issue need to go into IINA 1.4.2. I will ask the senior developers if they agree.

The other reason why  at this time we are trying to limit functionality that introduces new settings is because the project has started to address technical debt. The way IINA's UI is coded (XIB files) is now 2 generations behind. Work is underway to update the UI to SwiftUI, starting with settings. You can see that work in the [new-pref-ui](https://github.com/iina/iina/tree/new-pref-ui) branch. Any changes to the current settings code will have to be adapted and added to the new code.

My opinion is that for the case at hand we make the change to the old code for 1.4.2 and accept the need to adapt those changes to the Swift UI version of IINA's settings.

**Comment by low-batt** [comment]
@Cykelero I heard back from the senior developers. They approve.

**Comment by Cykelero** [comment]
Thank you for the look behind the scenes, that's interesting! Migrating the settings to SwiftUI sounds like a good plan.

#5868 is now open, and implements the changes.

**Comment by anohren** [comment]
The coarseness of this option has always bugged me in every player, come to think of it. Good initiative. 

I thought I'd ask if this fixes #2277? Haven't used that service for some time though so maybe it was fixed by accident already. 

One suggestion: Shouldn't the option be called "Prefer multiple player windows"? "Allow" sounds like it'll only happen in corner-cases, and not as a rule. My understanding is that this will actually be the preferred behavior when enabled, except for in corner-cases that are clearly spelled out as sub-options.

**Comment by Cykelero** [comment]
The PR doesn’t fix #2277, sorry. Looking at the code, URL opening uses very different code paths from regular file opening, and it’d take some work to refactor everything to correctly honor the settings, and not break anything. (for curious devs: `PlayerCore.openURLString(_:)` is an instance method, doesn’t always call `PlayerCore.openURLs(_:shouldAutoLoad:)`, and itself has a bunch of different callers)

Naming the option “Prefer multiple player windows” would suggest that when unchecked, multiple windows are still possible—but they’re not (well, not easily, anyway). “Allow” conveys that meaning correctly, although I agree that it doesn’t convey how often you’ll see multiple windows, either. So far this is the best wording I could find, though!

**Comment by anohren** [comment]
> The PR doesn’t fix [#2277](https://github.com/iina/iina/issues/2277), sorry

Thanks for taking a look! I just had a nagging feeling that I'd run into a problem like this before, and thought I'd link it in for reference in case it was an easy fix.


With reservations for having misunderstood this feature somehow:

> Naming the option “Prefer multiple player windows” would suggest that when unchecked, multiple windows are still possible—but they’re not (well, not easily, anyway). “Allow” conveys that meaning correctly, although I agree that it doesn’t convey how often you’ll see multiple windows, either. So far this is the best wording I could find, though!

I don't know about you, but when I adjust preferences I'd like to know what is actually going to happen when I e.g. double click two files in succession, without having to perform tests to understand the change in behavior. The benefit is that "Prefer" informs users of that, while "Allow" doesn't. I think the wording of settings should focus on communicating the actual behavior, without users having to guess. 

And as you say, unchecking this option doesn't prevent you from using multiple windows, so there's no implied contradiction here. In other words, I don't see a problem with suggesting something that's true, especially when there are other benefits. 

In short:
* IINA always has, and always will, allow you to open multiple windows, so in essence, "Allow" does not give the user any new information about how IINA's behavior changes.
* "Prefer" conveys the most important aspect of this feature: "Opening two files after each other will open two windows". The "Allow" wording doesn't convey this, in favor of focusing on a less important aspect of the feature: "When unchecked it's *slightly* more work (not impossible) to open files in multiple windows" (something that is already implied in the feature).

For the reasons above I strongly disagree that "Allow" is the best choice of words here. Anyway, this is my attempt to alleviate these problems in the least invasive change I could think of. But I'll leave it to you and the others to think about it.

**Comment by anohren** [comment]
I might have misread you though, I'll take a look at that.

Edit: yeah I did, sorry if I caused any confusion. I edited out the parts I got back to front, but I think my main point still stands. Let me know if I've still misunderstood something 🙂

**Comment by ellarsee** [comment]
Yeah, I've been fighting with this.
What I want to happen, and what did happen in 1.3:
If I select a group of files and open them, they open in a window
If I select another group of files (or another file) and open them, they open in another window.

What happens now.
If I select always open in new window, if I select a group of files, then each and every one of them opens in a new window.
If I disable always open in a new window and I select a group of files, they will all open in that window.
BUT if I select another file, or group of files, they all open in the same window that was already open.

So, what I think I want if I understand the terminology correctly is:
Every time I "start IINA" I want it to open a new window, but with all of the files selected in a playlist.

I don't exactly know swift, but if you can point me to the file(s) to look at, I might be able to hack together a fix for my own system.

**Comment by Cykelero** [comment]
@ellarsee Not to worry, this is a behavior that’ll be supported once #5868 is merged and published. The releasing will take some more time still, but the coding part is essentially done!

**Comment by Robio** [comment]
This looks like it would address my UX issues. Looking forward to its implementation!

**Comment by low-batt** [comment]
Thanks to @Cykelero it has been implemented. This is what the `Behavior` section on the `General` tab of IINA's settings looks like in the development version of IINA:

![Image](https://github.com/user-attachments/assets/a785c486-1328-493f-b88f-7d1a80a10d58)

Currently other changes and fixes for the next IINA release are being reviewed and merged. That work is bringing us closer to a release which will include the change in this pull request.

**Comment by Robio** [comment]
Just downloaded 1.4.2. SOOO happy! Thanks @low-batt

**Comment by Cykelero** [comment]
@Robio Glad you're happy with the result 😊 Thank you for coming back to comment.
